### ISSUE TITLE
Broken since Firefox 117

### ISSUE THREAD

**Issue by nicolaasjan** [earthlng/aboutconfig#10]
Loading `chrome://userchromejs/content/aboutconfig/config.xhtml`
Now gives:

![Screenshot_2023-08-03](https://github.com/earthlng/aboutconfig/assets/14093220/b6613833-288e-40b3-9ced-18de5559627f)

Clicking on "I accept the risk!" does nothing.

**Comment by earthlng** [comment]
Hi,

thx for reporting. FF117 Release will be out in a couple of days and I'll check it out then.

In the meantime, can you please check if replacing the following line in config.js, fixes it?

replace this:
```js
const { Services } = ChromeUtils.import("resource://gre/modules/Services.jsm");
```

with this:
```js
const Services = globalThis.Services || ChromeUtils.import("resource://gre/modules/Services.jsm").Services;
```

thanks

**Comment by nicolaasjan** [comment]
It worked! 🌻
In Firefox 116.0.3, 117.0b9 and Nightly 118.0a1 (2023-08-27).

**Comment by nicolaasjan** [comment]
Though there is no scrollbar in Fx 116.0.3:

![Screenshot_20230827-3](https://github.com/earthlng/aboutconfig/assets/14093220/f9358cf1-61eb-43e8-bbfb-2edbdc6d2502)

There is one in 117.0b9 and Nightly 118.0a1:

![Screenshot_20230827-4](https://github.com/earthlng/aboutconfig/assets/14093220/f3645d97-ea42-4225-99aa-aa33e3644aea)
