### ISSUE TITLE
Figured you might want this

### ISSUE THREAD

**Issue by aminomancer** [earthlng/aboutconfig#2]
I recently found a way to register a new `about:` URL and figured it'd be a pretty good match for this. I just registered your config document to `about:cfg`, which looks a bit fancier than a long chrome:// path — [here's the script](https://github.com/aminomancer/uc.css.js/blob/master/script/aboutCfg.uc.js). Apologies if you already knew about this and passed on it. If you want to include it, it's pretty simple. The script contents can just be appended to the end of your boot.jsm file. But you can just replace `findAboutConfig()` with `chrome://userchromejs/content/aboutconfig/config.xhtml` if you don't care about supporting other possible chrome paths/autoconfig loaders.

**Comment by earthlng** [comment]
hey, thanks for sharing, that's really neat !

but I'm not sure I want to add that because
1) I want to keep the code to a bare minimum, simple and lightweight
2) I don't fully understand the ins+outs of all those various flags

fe [here](https://searchfox.org/mozilla-central/source/toolkit/components/normandy/content/AboutPages.jsm#86) they only add the channel.owner when the `URI_SAFE_FOR_UNTRUSTED_CONTENT` flag is set.

I know the URL is not ideal but I just bookmarked it as "about:config" and now it shows up as the 1st link in the urlbar dropdown list when I start typing `about`. Maybe not for everybody but it works for me.

We can keep this issue open so other people who might be interested can see it and maybe I'll come back to it later or I'll add a link to your script to my README.

**Comment by aminomancer** [comment]
fair enough. I already tested it extensively, it can't navigate to remote and uses the system principal which is what's desired here since it's changing user preferences. the newChannel function is a security restriction, not security elevation. as for the system principal, that's the safest option. if it used a content principal then who knows what might happen if a user's virus happened to modify the config.xhtml file. it might open an xmlhttprequest to some malicious remote address, not that I really know if there are viruses that target autoconfig files lol. actually the allow script flag doesn't seem to do anything, but I tried to stick to conventions.

as for the normandy page, that's because that particular page has to link to a bunch of other pages which have different principals. it could get blocked otherwise since some of the about pages aren't allowed to be linked to from content principals, or have to run in extension process even. but the about config page doesn't have any restrictions so I just modeled it after the way the old pre-87 one was configured. the flags are described [here](https://searchfox.org/mozilla-central/source/netwerk/protocol/about/nsIAboutModule.idl) if you're curious.

and yeah it's true that you can bookmark the page, but the urlbar autofill provider autocompletes genuine about: addresses, after user types about: that is. it takes over from there bc it happens earlier in the block, so once you type that far it rules out any bookmarks/history/engines/etc. that would otherwise be autofilled. plus it only shows up in the about:about page if it's registered as a component.

it's actually the same thing you're already doing with `registrar.autoRegister(manifest)`, it just has extra security features. while I was researching for this I found that chrome:// URIs are much less restricted than about: pages. it's referenced in several places in the comments for these about modules (like in AboutRedirector.cpp) that about pages use CSP for example. it seems like that's the reason about pages were added in the first place. the only chrome:// paths I've seen the browser link to without redirecting them are displayed in special browsers that can't navigate outside. like the places library

**Comment by earthlng** [comment]
@aminomancer 

I finally got around to adding your code to this project. Thanks again for writing that awesome code and for letting me use it here!

**Comment by aminomancer** [comment]
Looks nice, no problem 👍
