### ISSUE TITLE
Doesn't seem to work with the latest Nightly version

### ISSUE THREAD

**Issue by DumZee** [earthlng/aboutconfig#3]
So, when I try to open chrome://userchromejs/content/aboutconfig/config.xhtml , my Nightly version 101.0a1 (2022-04-07) (64-bit) gives me a "File not found" error.

Did Mozilla change something, that made even the workaround method dead?

**Comment by earthlng** [comment]
IDK, but I'll have a look. Thanks

**Comment by earthlng** [comment]
fixed
