### ISSUE TITLE
In the Mozilla team's desperate efforts to fix what's not broken, they've once again broke your code...

### ISSUE THREAD

**Issue by DumZee** [earthlng/aboutconfig#7]
So, yeah, ummm..... I don't know what they did this time, but with version: "107.0a1 (2022-09-30) (64-bit)" all I'm getting is the warning page:
![ff](https://user-images.githubusercontent.com/79674440/193376287-c719950b-bb41-4b8e-a534-9b63e5f452c1.png)

But when I click "I accept the risk!" , nothing happens....
🥺

**Comment by LOuroboros** [comment]
Damn, this has been going for 20 days?

I just noticed it myself in v107.0b3 😔 ...

**Comment by earthlng** [comment]
I'll try to fix it when 107 gets released

**Comment by earthlng** [comment]
should be fixed now

**Comment by LOuroboros** [comment]
Can confirm. It's working nicely in the v107.0 👍

**Comment by earthlng** [comment]
Great! Thx for the feedback 👍
