### ISSUE TITLE
Dosent work on Firefox tete009 & origin ver 106.0.5

### ISSUE THREAD

**Issue by BliemHax** [earthlng/aboutconfig#8]
I typed about:cfg, but it was all white. I checked all the steps myself and they are correct.
Device: Windows 10 Chinese
Tested on Firefox tete009 106.0.5 Chinese and Mozilla Firefox 106.0.5 Chinese, both failed.
![Capture20221125162235](https://user-images.githubusercontent.com/58077798/203935136-1e3f9ebd-733d-4b90-9a86-e794f8f385b1.png)

**Comment by earthlng** [comment]
Thanks for reporting this problem. It's fixed in the new aboutcfg.jsm
